inventory/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # ex: /inv/5/
    url(r'^set/(?P<set_id>[0-9]+)/$', views.cardset, name='cardset'),
    # ex: /inv/card/5
    url(r'^card/(?P<card_id>[0-9]+)/$', views.card_details, name='card_details'),
    # ex: /inv/search/card_search_box=island
    url(r'^search/.*$', views.search, name='search'),
    # ex: /inv/autocomplete/
    url(r'^autocomplete/.*$', views.autocomplete, name='autocomplete'),
    # ex: /inv/pricing/
    url(r'^pricing/.*$', views.pricing_ajax),
]

midgard/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

import inventory.views
import common.util.SetParser
import common.util.CardParser
import common.util.PriceUpdater

urlpatterns = [
    url(r'^inv/', include('inventory.urls', namespace='inventory')),
    url(r'^login', auth_views.login, name='login'),
    url(r'^logout', auth_views.logout, {'next_page': '/inv/'}, name='logout'),
    url(r'^pricing/', inventory.views.pricing),
    url(r'^admin/', admin.site.urls),
    url(r'^signup/', inventory.views.signup, name='signup'),
    url(r'^parse_all_sets/', common.util.SetParser.parse_all_sets),
    url(r'^parse_all_cards/', common.util.CardParser.parse_all_cards),
    url(r'^create_all_prices/', common.util.PriceUpdater.create_all_prices),
]

inventory/models.py
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.search import SearchVectorField
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=150, blank=True)
    other_address = models.CharField(max_length=150, blank=True)
    city = models.CharField(max_length=100, blank=True)
    province = models.CharField(max_length=2, blank=True)
    country = models.CharField(max_length=50, blank=True)
    postal_code = models.CharField(max_length=10, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    phone_number = models.CharField(max_length=20, blank=True)


class MagicSet(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=10)
    release_date = models.DateField()
    cards_in_set = models.IntegerField(default=0)

    class Meta:
        unique_together = ('name', 'code', 'release_date')

    def __str__(self):
        return self.name


class MagicCard(models.Model):
    RARITIES = (
        ('C', 'Common'),
        ('U', 'Uncommon'),
        ('R', 'Rare'),
        ('M', 'Mythic'),
        ('B', 'Basic Land'),
    )

    COLORS = (
        ('W', 'White'),
        ('U', 'Blue'),
        ('B', 'Black'),
        ('R', 'Red'),
        ('G', 'Green'),
        ('C', 'Colorless'),
    )

    LANGUAGES = (
        ('EN', 'English'),
        ('CT', 'Chinese (Traditional)'),
        ('CS', 'Chinese (Simplified)'),
        ('FR', 'French'),
        ('DE', 'German'),
        ('IT', 'Italian'),
        ('JP', 'Japanese'),
        ('KR', 'Korean'),
        ('PT', 'Portuguese'),
        ('RU', 'Russian'),
        ('ES', 'Spanish'),
        ('OT', 'Other'),
    )

    name = models.CharField(max_length=170)
    set = models.ForeignKey(MagicSet)
    color = ArrayField(models.CharField(max_length=1, choices=COLORS))
    color_text = models.CharField(max_length=50)
    color_identity = ArrayField(models.CharField(max_length=1, choices=COLORS))
    layout_type = models.CharField(max_length=50, default='normal')
    ordered_card_names = ArrayField(models.CharField(max_length=170), null=True)
    is_focal_card = models.BooleanField(default=True)
    super_types = ArrayField(models.CharField(max_length=40), null=True)
    super_types_text = models.CharField(max_length=100, blank=True)
    types = ArrayField(models.CharField(max_length=40), null=True)
    types_text = models.CharField(max_length=100, blank=True)
    sub_types = ArrayField(models.CharField(max_length=40), null=True)
    sub_types_text = models.CharField(max_length=100, blank=True)
    mana_cost = models.CharField(max_length=100, default='')
    cmc = models.IntegerField(default=0)
    card_language = models.CharField(max_length=15, choices=LANGUAGES, default='EN')
    rules_text = models.TextField(blank=True)
    flavor_text = models.TextField(blank=True)
    collector_number = models.CharField(max_length=8)
    multiverse_id = models.IntegerField(null=True)
    artist = models.CharField(max_length=100)
    image = models.ImageField(upload_to='inventory/static/images/', default='images/None/no_art.jpg', max_length=300)
    rarity = models.CharField(max_length=1, choices=RARITIES)
    power = models.CharField(max_length=5, blank=True)
    toughness = models.CharField(max_length=5, blank=True)
    card_search = SearchVectorField(db_index=True, null=True)

    class Meta:
        unique_together = ('name', 'set', 'card_language', 'collector_number', 'multiverse_id')

    def __str__(self):
        return self.name


class MagicCardItem(models.Model):
    NM = 'NM'
    SP = 'SP'
    MP = 'MP'
    HP = 'HP'
    CONDITIONS = (
        (NM, 'Near Mint'),
        (SP, 'Slightly Played'),
        (MP, 'Moderately Played'),
        (HP, 'Heavily Played')
    )
    card = models.ForeignKey(MagicCard)
    price = models.FloatField(default=-1)
    buylist = models.FloatField(default=-1)
    stock = models.IntegerField(default=0)
    condition = models.CharField(max_length=2, choices=CONDITIONS)
    foil = models.BooleanField()

    class Meta:
        unique_together = ('card', 'condition', 'foil')


class Item(models.Model):
    name = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    price = models.FloatField(default=-1)
    magic_set = models.ForeignKey(MagicSet, blank=True)

    class Meta:
        unique_together = ('name', 'type')


class Transaction(models.Model):
    BUY = 'BUY'
    DIST = 'DIST'
    SELL = 'SELL'
    CHARITY = 'CHARITY'
    DISCARD = 'DISCARD'
    TRANSACTION_TYPES = (
        (BUY, 'Purchase from Customer'),
        (DIST, 'Distributor Purchase'),
        (SELL, 'Sell'),
        (CHARITY, 'Charitable Donation'),
        (DISCARD, 'Discarded'),
    )
    customer = models.ForeignKey(User, blank=True)
    distributor = models.CharField(max_length=100)
    charity = models.CharField(max_length=100)
    quantity = models.IntegerField()
    price = models.FloatField()
    magic_card = models.ForeignKey(MagicCardItem, blank=True)
    item = models.ForeignKey(Item, blank=True)
    type = models.CharField(max_length=10, choices=TRANSACTION_TYPES)
    provincial_tax = models.FloatField()
    federal_tax = models.FloatField()

inventory/forms.py
from django import forms
from django.forms import extras
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django_countries import countries
from localflavor.ca.forms import CAPhoneNumberField, CAPostalCodeField, CAProvinceField, CAProvinceSelect

from inventory.models import Profile


class UserForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=254, help_text='Required')

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        )


class ProfileForm(forms.ModelForm):
    model = Profile
    street_address = forms.CharField(max_length=150)
    other_address = forms.CharField(max_length=150, required=False)
    city = forms.CharField(max_length=100)
    province = CAProvinceField(widget=CAProvinceSelect)
    country = forms.ChoiceField(choices=list(countries))
    postal_code = CAPostalCodeField
    birth_date = forms.DateField(widget=extras.SelectDateWidget)
    phone_number = CAPhoneNumberField()

    class Meta:
        model = Profile
        fields = (
            'street_address',
            'other_address',
            'city',
            'province',
            'country',
            'postal_code',
            'birth_date',
            'phone_number',
        )

inventory/views.py
import json

from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, HttpResponseNotFound
from django.template import loader
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect
from django.views import generic

from inventory.templatetags.card_filters import replace_symbols
from .models import MagicCard, MagicSet
from .forms import UserForm, ProfileForm


class IndexView(generic.ListView):
    template_name = 'inventory/index.html'
    context_object_name = 'set_list'

    def get_queryset(self):
        return MagicSet.objects.order_by('-release_date')


class MagicSetView(generic.ListView):
    model = MagicCard
    template_name = 'inventory/cardlist.html'

    def get_queryset(self):
        return MagicCard.objects


class SearchView(generic.ListView):
    model = MagicCard
    template_name = 'inventory/cardlist.html'

    def get_queryset(self):
        return MagicCard.objects


class MagicCardDetailsView(generic.DetailView):
    model = MagicCard
    template_name = 'inventory/carddetails.html'


def index(request):
    set_list = MagicSet.objects.order_by('-release_date')
    template = loader.get_template('inventory/index.html')
    context = {
        'set_list': set_list,
    }
    return render(request, 'inventory/index.html', context)


def cardset(request, set_id):
    card_list = get_list_or_404(MagicCard.objects.order_by('name'), set=set_id)
    paginator = Paginator(card_list, 25)
    page = request.GET.get('page')
    try:
        cards = paginator.page(page)
    except PageNotAnInteger:
        cards = paginator.page(1)
    except EmptyPage:
        cards = paginator.page(paginator.num_pages)
    return render(request, 'inventory/cardlist.html', {'card_list': cards})


def search(request):
    if request.method == 'GET':
        query = request.GET.get('card_search_box', None)
        vector = SearchVector('name', weight='A') + \
            SearchVector('super_types_text', 'types_text', 'sub_types_text', weight='B') + \
            SearchVector('rules_text', weight='C') + \
            SearchVector('color_text', 'power', 'toughness', 'artist', 'flavor_text', weight='D')
        search_query = SearchQuery(query)
        card_list = MagicCard.objects.annotate(
            search=vector,
            rank=SearchRank(vector, search_query)
        ).filter(card_search=query).order_by('-rank', 'name')
        paginator = Paginator(card_list, 25)
        page = request.GET.get('page')
        try:
            cards = paginator.page(page)
        except PageNotAnInteger:
            cards = paginator.page(1)
        except EmptyPage:
            cards = paginator.page(paginator.num_pages)
        return render(request, 'inventory/search.html', {'card_list': cards, 'query': query})


def autocomplete(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        cards = MagicCard.objects \
            .filter(name__icontains=q) \
            .exclude(image='/images/None/no_art.jpg') \
            .order_by('name', 'set__release_date').distinct('name')[:10]
        results = []
        for card in cards:
            card_json = {
                'label': card.name,
                'value': card.name,
                'desc': replace_symbols(card.rules_text),
                'id': card.id,
                'image': str(card.image),
            }
            results.append(card_json)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)


def card_details(request, card_id):
    card = get_object_or_404(MagicCard, pk=card_id)
    return render(request, 'inventory/carddetails.html', {'card': card})


def pricing(request):
    if request.user.groups.filter(name='Employees').exists():
        return render(request, 'inventory/pricing.html')
    else:
        return HttpResponseNotFound()


def pricing_ajax(request):
    if request.is_ajax():
        q = request.GET.get('name', '')
        cards = MagicCard.objects.filter(name=q).order_by('-set__release_date', 'set__name')[:64]
        condition_order = {
            'NM': 1,
            'SP': 2,
            'MP': 3,
            'HP': 4,
        }
        cards = sorted(cards, key=lambda x: condition_order[x.condition])
        results = []
        for card in cards:
            card_json = {
                'name': card.name,
                'set': card.set.name,
                'condition': card.condition,
                'price': card.price,
            }
            results.append(card_json)
        data = json.dumps(results)
    else:
        data = 'nope'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)


def signup(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user_profile = profile_form.save(commit=False)
            user_profile.user = user
            user_profile.save()
            username = user_form.cleaned_data.get('username')
            raw_password = user_form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/inv/')
    else:
        user_form = UserForm()
        profile_form = ProfileForm()
    return render(request, 'inventory/signup.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })

templates/inventory/base.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'inventory/css/style.css' %}" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" type="text/css" media="all" />
<link rel="stylesheet" href="{% static 'inventory/css/keyrune.css' %}" type="text/css" />
<script src="https://code.jquery.com/jquery-1.12.4.js" type="text/javascript"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" type="text/javascript"></script>
<body>
{% block autocomplete_script %}
    <script src="{% static 'inventory/js/autocomplete.js' %}"type="text/javascript"></script>
{% endblock %}
{% block search_form %}
    <form id="search_form" name="search_form" type="get" action="/inv/search/" style="margin: 0">
        <input id="card_search_box" type="text" name="card_search_box" placeholder="Search for a card..." >
        <button id="search_submit" type="submit">Submit</button>
    </form>
{% endblock %}
<div id="login-status" class="pull-right">
    {% if user.is_authenticated %}
        Logged in as {{ user }}. <a href="{% url 'logout' %}">(logout)</a>
    {% else %}
        Note currently logged in.
        <a href="{% url 'login' %}">Please Login</a>
        <a href="{% url 'signup' %}">(signup)</a>
    {% endif %}
</div>
    {% block content %}
    {% endblock %}
</body>

templates/inventory/carddetails.html
{% extends "inventory/base.html" %}
{% load staticfiles %}
{% load card_filters %}
{% block content %}
    {% if card %}
        <table class="table">
        <tr>
            <td>{{ card.name }}</td>
            <td class="fit" rowspan="5"><img src="{% static card.image %}" /></td>
        </tr>
        <tr>
            <td>{{ card.mana_cost | replace_symbols | safe }}</td>
        </tr>
        <tr>
            <td>{{ card.super_types_text }} {{ card.types_text }} {{ card.sub_types_text | insert_subtypes }}</td>
            <td></td>
            <td>{{ card.price }}</td>
        </tr>
        <tr>
            <td>
                {% autoescape on %}
                    {{ card.rules_text | replace_symbols | italicize_reminder_text | safe | linebreaksbr}}
                {% endautoescape %}
            </td>
        </tr>
        <tr>
            <td>
                {% autoescape on %}
                    <i>{{ card.flavor_text | linebreaksbr}}</i>
                {% endautoescape %}
            </td>
        </tr>
        </table>
    {% endif %}
{% endblock %}

templates/inventory/cardlist.html
{% extends "inventory/base.html" %}
{% load staticfiles %}
{% block content %}
    {% if card_list %}
        <div class="pagination">
            <span class="step-links">
                {% if card_list.has_previous %}
                    {% block prev_page_top %}
                        <a href="?page={{ card_list.previous_page_number }}">previous</a>
                    {% endblock %}
                {% endif %}

                <span class="current">
                    Page {{ card_list.number }} of {{ card_list.paginator.num_pages }}
                </span>

                {% if card_list.has_next %}
                    {% block next_page_top %}
                        <a href="?page={{ card_list.next_page_number }}">next</a>
                    {% endblock %}
                {% endif %}
            </span>
        </div>
        <table class="table table-hover table-striped table-small">
            <tr>
                <th class="fit"></th>
                <th>Name</th>
                <th>Set</th>
                <th>Stock</th>
                <th>Price</th>
            </tr>
            {% for card in card_list %}
                <tr>
                    <td class="fit"><img src="{% static card.image %}" alt="{{ card.name }}" class="stock-table-image"/></td>
                    <td><a href="{% url 'inventory:card_details' card.id %}">{{ card.name }}</a></td>
                    <td><a href="{% url 'inventory:cardset' card.set.id %}">{{ card.set }}</a></td>
                    <td>{{ card.stock }}</td>
                    <td>${{ card.price|floatformat:2 }}</td>
                </tr>
            {% endfor %}
        </table>
        <div class="pagination">
            <span class="step-links">
                {% if card_list.has_previous %}
                    {% block prev_page_bottom %}
                        <a href="?page={{ card_list.previous_page_number }}">previous</a>
                    {% endblock %}
                {% endif %}

                <span class="current">
                    Page {{ card_list.number }} of {{ card_list.paginator.num_pages }}
                </span>

                {% if card_list.has_next %}
                    {% block next_page_bottom %}
                        <a href="?page={{ card_list.next_page_number }}">next</a>
                    {% endblock %}
                {% endif %}
            </span>
        </div>
    {% else %}
    <p>There aren't any cards!!</p>
    {% endif %}
{% endblock %}

templates/inventory/index.html
{% extends "inventory/base.html" %}
{% block content %}
    {% if set_list %}
        <ul>
            {% for set in set_list %}
                <li><a href="{% url 'inventory:cardset' set.id %}">{{ set }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
    <p>There aren't any sets!!</p>
    {% endif %}
{% endblock %}

templates/inventory/pricing.html
{% extends 'inventory/base.html' %}
{% load staticfiles %}
{% block autocomplete_script %}
{% endblock %}
{% block search_form %}
    <input id="card_search_box" type="text" name="card_search_box" placeholder="Search for a card..." >
{% endblock %}
{% block content %}
    <script src="{% static 'inventory/js/hoverphoto.js' %}" type="text/javascript"></script>
    <script src="{% static 'inventory/js/populatePricingTable.js' %}" type="text/javascript"></script>
    <button>TEST</button>
    <div id="test-table"></div>
    <table id="pricing-table" class="table table-striped table-bordered table-sm table-nonfluid">
    <tbody>
        <tr>
            <th colspan="7">Aven Mindcensor</th>
        </tr>
       <tr>
            <th>Set</th>
            <td class="set-row" colspan="2">
                <figure class="card-picture">
                    <img src="{% static 'images/AKH/Aven_Mindcensor_426707.jpg' %}">
                </figure>
                <i class="ss ss-akh ss-2x"></i> &#x2014; Amonkhet
            </td>
            <td class="set-row" colspan="2">
                <figure class="card-picture">
                    <img src="{% static 'images/MPS_AKH/Aven_Mindcensor_429861.jpg' %}">
                </figure>
                <i class="ss ss-mp2 ss-2x"></i> &#x2014; Amonkhet Invocations
            </td>
            <td class="set-row" colspan="2">
                <figure class="card-picture">
                    <img src="{% static 'images/FUT/Aven_Mindcensor_136204.jpg' %}">
                </figure>
                <i class="ss ss-fut ss-2x"></i> &#x2014; Future Sight
            </td>
        </tr>
        <tr>
            <th>NM</th>
            <td>$1.99</td>
            <td>($9.99)</td>
            <td>$40.99</td>
            <td>(N/A)</td>
            <td>$8.99</td>
            <td>($46.99)</td>
        </tr>
        <tr>
            <th>SP</th>
            <td>$1.79</td>
            <td>($8.99)</td>
            <td>$36.99</td>
            <td>(N/A)</td>
            <td>$7.99</td>
            <td>($41.99)</td>
        </tr>
        <tr>
            <th>MP</th>
            <td>$1.49</td>
            <td>($7.49)</td>
            <td>$29.99</td>
            <td>(N/A)</td>
            <td>$6.99</td>
            <td>($34.99)</td>
        </tr>
        <tr>
            <th>HP</th>
            <td>$0.99</td>
            <td>($4.89)</td>
            <td>$19.99</td>
            <td>(N/A)</td>
            <td>$4.49</td>
            <td>($23.99)</td>
        </tr>
    </tbody>
    </table>
{% endblock %}

templates/inventory/search.html
{% extends "inventory/cardlist.html" %}
{% block prev_page_top %}
    <a href="?card_search_box={{ query }}&page={{ card_list.previous_page_number }}">back</a>
{% endblock %}
{% block next_page_top %}
    <a href="?card_search_box={{ query }}&page={{ card_list.next_page_number }}">forward</a>
{% endblock %}
{% block prev_page_bottom %}
    <a href="?card_search_box={{ query }}&page={{ card_list.previous_page_number }}">back</a>
{% endblock %}
{% block next_page_bottom %}
    <a href="?card_search_box={{ query }}&page={{ card_list.next_page_number }}">forward</a>
{% endblock %}

templates/inventory/set.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'inventory/style.css' %}" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
{% if card_list %}
    <table class="table table-hover table-striped table-small">
        <tr>
            <th class="fit"></th>
            <th>Name</th>
            <th>Set</th>
            <th>Stock</th>
            <th>Price</th>
        </tr>
        {% for card in card_list %}
            <tr>
                <td class="fit"><img src="{% static card.image %}" alt="{{ card.name }}" class="stock-table-image"/></td>
                <td>{{ card.name }}</td>
                <td>{{ card.set.code }}</td>
                <td>{{ card.stock }}</td>
                <td>${{ card.price|floatformat:2 }}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
<p>There aren't any cards!!</p>
{% endif %}

templates/inventory/signup.html
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">Sign up</button>
</form>